version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=latest
      - PLEX_CLAIM= #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /opt/plex/config:/config
      - /mnt/nas/plex/Movies:/movies
      - /mnt/nas/plex/TV:/tv
      - /mnt/nas/plex/Sports:/sports
      - /mnt/nas/plex/Movies4k:/movies4k
      - /mnt/nas/plex/MoviesNew:/moviesNew
    runtime: nvidia
    restart: unless-stopped