name: CI
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'docker/**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'docker/**/README.md'    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validateComposeSyntax:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Loops over all compose files and uses docker compose check for YML validation
      - name: DockerComposeCheck
        run: |
          for f in $(find ${PWD}/docker -name '*docker-compose*.yml'); \
          do \
          readlink -f $f && \
          docker compose -f $(readlink -f $f) config --quiet; \
          done
        if: always()